import type { OperatorEntry } from "@/lib/types";
import { MISSIONS } from "@/lib/challenges/data";

function linkedFor(op: string): string[] {
  return MISSIONS.filter((m) => m.operators.includes(op)).map((m) => m.id);
}

function entry(partial: Omit<OperatorEntry, "linkedChallengeIds">): OperatorEntry {
  return { ...partial, linkedChallengeIds: linkedFor(partial.name) };
}

export const OPERATORS: OperatorEntry[] = [
  entry({
    stage: true,
    name: "$match",
    category: "stage",
    syntax: '{ $match: { <field>: <condition> } }',
    purpose: "Filters documents before any other work. Put it first: it shrinks the working set and makes every later stage faster.",
    example: '{ $match: { status: "delivered", total: { $gte: 250 } } }',
    exampleOutput: "Only orders that are delivered AND total at least 250.",
    realWorld: "Status-driven reports, event streams filtered by state, security scoping.",
    commonMistakes: ["Matching too late in the pipeline", "Using an operator that is not index-friendly on huge collections", "Forgetting that separate top-level fields combine as logical AND"],
    performanceTips: ["Always $match before $group, $sort or $lookup", "Match on indexed fields whenever possible", "Use $in instead of several OR conditions"],
    related: ["$expr", "$in", "$gte", "$lt"],
  }),
  entry({
    stage: true,
    name: "$project",
    category: "stage",
    syntax: '{ $project: { <field>: <1|0|expression> } }',
    purpose: "Reshapes each document: include, exclude or compute fields. The go-to stage for hiding internal identifiers.",
    example: '{ $project: { _id: 0, orderNumber: 1, total: 1, totalWithTax: { $multiply: ["$total", 1.2] } } }',
    exampleOutput: "A lean document with orderNumber, total and a computed totalWithTax.",
    realWorld: "API response shaping, hiding internal fields before sending data to clients.",
    commonMistakes: ["Returning extra fields the expected output does not include", "Mixing inclusion and exclusion modes (except _id)", "Forgetting that nested fields need dot paths or computed objects"],
    performanceTips: ["Project late — after filtering shrinks the set", "Only carry the fields later stages need", "$project before $match can materialize data that gets filtered"],
    related: ["$addFields", "$expr"],
  }),
  entry({
    stage: true,
    name: "$addFields",
    category: "stage",
    syntax: '{ $addFields: { <newField>: <expression> } }',
    purpose: "Adds new fields to every document while keeping all existing fields.",
    example: '{ $addFields: { lifetimeValue: { $multiply: ["$totalSpent", 1.1] } } }',
    exampleOutput: "Same document, plus a lifetimeValue field.",
    realWorld: "Enriching documents with computed scores before sorting.",
    commonMistakes: ["Using it when $project is cheaper (if you also remove fields)", "Overwriting an existing field accidentally"],
    performanceTips: ["Prefer it over $project when you keep all fields", "Compute once, reuse via variables"],
    related: ["$project", "$setWindowFields"],
  }),
  entry({
    stage: true,
    name: "$group",
    category: "stage",
    syntax: '{ $group: { _id: <groupBy>, <acc>: <accumulator> } }',
    purpose: "Groups documents by an _id expression and runs accumulators ($sum, $avg, $min, $max) over each group.",
    example: '{ $group: { _id: "$status", count: { $sum: 1 }, avgTotal: { $avg: "$total" } } }',
    exampleOutput: "One document per status with a count and average total.",
    realWorld: "Funnel analysis, dashboards, per-category aggregates.",
    commonMistakes: ["Forgetting to sort grouped output (group order is not guaranteed)", "Using $push when $sum is enough", "Grouping on the wrong key shape (string vs object)"],
    performanceTips: ["Filter before grouping to scan fewer docs", "Group first, join later — 5 rows beat 520 for a lookup", "Use $sum: 1 as a counter"],
    related: ["$sort", "$sum", "$avg", "$min", "$max", "$first"],
  }),
  entry({
    stage: true,
    name: "$sort",
    category: "stage",
    syntax: '{ $sort: { <field>: <1|-1> } }',
    purpose: "Orders documents by one or more fields. Always sort before $limit for correct top-N.",
    example: '{ $sort: { total: -1, orderNumber: 1 } }',
    exampleOutput: "Documents ordered by total descending, ties by orderNumber ascending.",
    realWorld: "Leaderboards, best-sellers, 'top N' reports.",
    commonMistakes: ["Sorting after $limit so the wrong rows win", "Forgetting that group output needs a deterministic sort", "Assuming a stable order without sorting"],
    performanceTips: ["Sort only after filtering/grouping shrinks the set", "Sort on indexed fields to use the index", "Two-key sorts are cheap — add a tiebreaker for determinism"],
    related: ["$limit", "$group", "$setWindowFields"],
  }),
  entry({
    stage: true,
    name: "$limit",
    category: "stage",
    syntax: '{ $limit: <n> }',
    purpose: "Keeps only the first n documents. Combine with $sort to fetch top-N.",
    example: '{ $limit: 10 }',
    exampleOutput: "Only the first 10 documents.",
    realWorld: "Pagination, top-10 widgets, preview rows.",
    commonMistakes: ["Limiting before sorting", "Expecting $limit to return a random sample"],
    performanceTips: ["Sort then limit — the order matters", "Limit early when the tail of the stream is irrelevant"],
    related: ["$sort", "$sample", "$skip"],
  }),
  entry({
    stage: true,
    name: "$unwind",
    category: "stage",
    syntax: '{ $unwind: "<arrayPath>" }',
    purpose: "Deconstructs an array field so each element becomes its own document. Row explosion is the point.",
    example: '{ $unwind: "$items" }',
    exampleOutput: "One order with 3 items becomes 3 documents, each with a single items object.",
    realWorld: "Line-item analytics, log flattening, feeding star schemas.",
    commonMistakes: ["Unwinding before filtering empties the stream", "Unwinding multiple arrays without considering exponential blow-up", "Forgetting documents with empty arrays disappear"],
    performanceTips: ["Match first so you don't explode unnecessary rows", "Filter the array with $filter instead of unwinding when you can", "Unwind once, not in a loop"],
    related: ["$match", "$group", "$lookup"],
  }),
  entry({
    stage: true,
    name: "$lookup",
    category: "stage",
    syntax: '{ $lookup: { from, localField, foreignField, as } }',
    purpose: "Left outer join: attaches a matching-array from another collection. Supports sub-pipelines with let + $expr.",
    example: '{ $lookup: { from: "users", localField: "userId", foreignField: "_id", as: "user" } }',
    exampleOutput: "Each order gains a user array with the matching user document.",
    realWorld: "Customer 360 views, denormalising for dashboards, enrichment.",
    commonMistakes: ["Joining before shrinking the input set", "Unwinding a lookup array without guarding empty results", "Forgetting the result is always an array"],
    performanceTips: ["Aggregate first, join later", "Index the foreign field", "Use sub-pipelines with let/$expr for correlated lookups"],
    related: ["$unwind", "$expr", "$graphLookup", "$ifNull", "$size"],
  }),
  entry({
    stage: true,
    name: "$count",
    category: "stage",
    syntax: '{ $count: "<fieldName>" }',
    purpose: "Replaces the stream with a single document holding the count.",
    example: '{ $count: "totalProducts" }',
    exampleOutput: '{ "totalProducts": 140 }',
    realWorld: "Pagination totals, batch summaries.",
    commonMistakes: ["Using $group with $sum when $count is clearer"],
    performanceTips: ["Filter first to count a subset", "It is the cheapest possible aggregate"],
    related: ["$group", "$match"],
  }),
  entry({
    stage: true,
    name: "$facet",
    category: "stage",
    syntax: '{ $facet: { <outputField>: [<pipeline>] } }',
    purpose: "Runs several independent sub-pipelines over the same input in a single scan. Each output field holds an array of results.",
    example: '{ $facet: { total: [{ $group: { _id: null, sum: { $sum: "$total" } } }], byStatus: [{ $group: { _id: "$status", count: { $sum: 1 } } }] } }',
    exampleOutput: "One document with a total array and a byStatus array.",
    realWorld: "Dashboard widgets, multi-metric snapshots, parallel analytics.",
    commonMistakes: ["Expecting $facet to merge results", "Putting $facet twice in one pipeline (only one allowed)"],
    performanceTips: ["One scan answers many questions — great for dashboards", "Keep each sub-pipeline focused"],
    related: ["$group", "$match"],
  }),
  entry({
    stage: true,
    name: "$setWindowFields",
    category: "stage",
    syntax: '{ $setWindowFields: { partitionBy, sortBy, output: { <field>: { <func>: { ... } } } } }',
    purpose: "Computes values across a window (partitioned and ordered) — running totals, ranks, moving averages.",
    example: '{ $setWindowFields: { partitionBy: "$year", sortBy: { rating: -1 }, output: { rank: { $rank: {} } } } }',
    exampleOutput: "Each movie gets a rank within its year (1 = best rated).",
    realWorld: "Cumulative revenue, cohort retention, 'top N per group' dashboards.",
    commonMistakes: ["Forgetting to sort before a running total", "Confusing $rank with a plain counter", "Ignoring the default frame (unbounded to current)"],
    performanceTips: ["Sort or partition cheaply — the window follows sort order", "Prefer $setWindowFields over self-lookups for ranking"],
    related: ["$group", "$sort", "$rank"],
  }),
  entry({
    stage: true,
    name: "$graphLookup",
    category: "stage",
    syntax: '{ $graphLookup: { from, startWith, connectFromField, connectToField, as, maxDepth } }',
    purpose: "Recursively walks a graph (e.g. followers → followers of followers) and collects every reachable node.",
    example: '{ $graphLookup: { from: "followers", startWith: "$_id", connectFromField: "followsId", connectToField: "userId", as: "reach", maxDepth: 2 } }',
    exampleOutput: "Each user gains a reach array of users reachable within two hops.",
    realWorld: "Influencer detection, fraud rings, org charts, social reach.",
    commonMistakes: ["Wrong connectFromField/connectToField direction", "Forgetting maxDepth and exploding the result", "Not deduplicating reach counts"],
    performanceTips: ["Cap depth — BFS grows exponentially", "Index the connectToField", "Count with $size after de-duplication"],
    related: ["$lookup", "$size", "$addFields"],
  }),
  entry({
    stage: true,
    name: "$sortByCount",
    category: "stage",
    syntax: '{ $sortByCount: "<field>" }',
    purpose: "Shortcut for group-by-field + count + sort descending in one stage.",
    example: '{ $sortByCount: "$status" }',
    exampleOutput: "One document per status with count, sorted descending.",
    realWorld: "Tag frequency analysis, categorical rankings.",
    commonMistakes: ["Needing extra grouping after the count"],
    performanceTips: ["Use it instead of $group + $sort when you only need counts"],
    related: ["$group", "$sort"],
  }),
  entry({
    stage: true,
    name: "$sample",
    category: "stage",
    syntax: '{ $sample: { size: <n> } }',
    purpose: "Returns n random documents from the collection.",
    example: '{ $sample: { size: 5 } }',
    exampleOutput: "Five random documents.",
    realWorld: "A/B test buckets, data exploration, quality checks.",
    commonMistakes: ["Expecting $sample to respect sort order"],
    performanceTips: ["Use $match first to sample from a relevant subset"],
    related: ["$limit", "$match"],
  }),
  entry({
    stage: true,
    name: "$replaceRoot",
    category: "stage",
    syntax: '{ $replaceRoot: { newRoot: "<expression>" } }',
    purpose: "Promotes a nested document to the top level.",
    example: '{ $replaceRoot: { newRoot: "$user" } }',
    exampleOutput: "The nested user object becomes the whole document.",
    realWorld: "Normalising data after lookups, promoting join results.",
    commonMistakes: ["Using it before guarding missing documents"],
    performanceTips: ["Prefer $project field aliases when you only need a few nested fields"],
    related: ["$project", "$unwind"],
  }),
  entry({
    stage: true,
    name: "$unionWith",
    category: "stage",
    syntax: '{ $unionWith: { coll: "<name>", pipeline: [<pipeline>] } }',
    purpose: "Appends documents from another collection, optionally after a sub-pipeline.",
    example: '{ $unionWith: "auditLog" }',
    exampleOutput: "All documents from the current collection plus those from auditLog.",
    realWorld: "Combining current + archived records.",
    commonMistakes: ["Unioning collections with different schemas without shaping"],
    performanceTips: ["Shape each branch with a sub-pipeline before unioning"],
    related: ["$project", "$match"],
  }),

  // Expressions
  entry({
    stage: false,
    name: "$sum",
    category: "expression",
    syntax: '{ $sum: <number|field|expression> }',
    purpose: "Sums values. Inside $group it sums per group; as $sum: 1 it counts documents.",
    example: '{ $sum: "$total" }',
    exampleOutput: "The total of all totals in the group.",
    realWorld: "Revenue totals, inventory quantities.",
    commonMistakes: ["Passing a non-numeric field"],
    performanceTips: ["Used inside $group it streams — no materialisation"],
    related: ["$group", "$avg", "$count"],
  }),
  entry({
    stage: false,
    name: "$avg",
    category: "expression",
    syntax: '{ $avg: <field> }',
    purpose: "Average of a numeric field across a group or array.",
    example: '{ $avg: "$rating" }',
    exampleOutput: "The mean rating.",
    realWorld: "Average order value, satisfaction scores.",
    commonMistakes: ["Averaging arrays without unwinding or flattening correctly"],
    performanceTips: ["Combine with $round for presentation"],
    related: ["$group", "$sum", "$divide"],
  }),
  entry({
    stage: false,
    name: "$min / $max",
    category: "expression",
    syntax: '{ $min: <field> }',
    purpose: "Smallest/largest value in a group or array.",
    example: '{ $min: "$total" }',
    exampleOutput: "The cheapest order in the group.",
    realWorld: "Range checks, SLAs, anomaly spotting.",
    commonMistakes: ["Using $first when you actually want $min"],
    performanceTips: ["$min/$max can leverage indexes on sorted inputs"],
    related: ["$group", "$first"],
  }),
  entry({
    stage: false,
    name: "$size",
    category: "expression",
    syntax: '{ $size: "<arrayField>" }',
    purpose: "Length of an array.",
    example: '{ $size: "$orders" }',
    exampleOutput: "How many orders are in the joined array.",
    realWorld: "Counts of joined children, review counts.",
    commonMistakes: ["Calling $size on a non-array"],
    performanceTips: ["Pair with $ifNull when the array may be missing"],
    related: ["$lookup", "$ifNull", "$first"],
  }),
  entry({
    stage: false,
    name: "$multiply",
    category: "expression",
    syntax: '{ $multiply: [<expr>, <expr>] }',
    purpose: "Multiplies numbers.",
    example: '{ $multiply: ["$qty", "$price"] }',
    exampleOutput: "Line total = qty × price.",
    realWorld: "Revenue per line, commissions, taxes.",
    commonMistakes: ["Using * instead of the array form"],
    performanceTips: ["Combine with $sum for totals across groups"],
    related: ["$add", "$divide", "$subtract"],
  }),
  entry({
    stage: false,
    name: "$cond",
    category: "expression",
    syntax: '{ $cond: [<bool>, <ifTrue>, <ifFalse>] }',
    purpose: "Conditional value selection (ternary).",
    example: '{ $cond: [{ $gt: ["$orders", 0] }, { $divide: ["$totalSpent", "$orders"] }, 0] }',
    exampleOutput: "Average order value, or 0 when there are no orders.",
    realWorld: "Divide-by-zero guards, tiered pricing, flags.",
    commonMistakes: ["Swapping the branches", "Not guarding division"],
    performanceTips: ["Keep branches simple for readability"],
    related: ["$ifNull", "$expr", "$divide"],
  }),
  entry({
    stage: false,
    name: "$ifNull",
    category: "expression",
    syntax: '{ $ifNull: [<expr>, <fallback>] }',
    purpose: "Returns the expression, or a fallback when it is null/missing.",
    example: '{ $ifNull: [{ $first: "$likes.likes" }, 0] }',
    exampleOutput: "The like count, or 0 for posts nobody liked.",
    realWorld: "Filling empty lookups, defaulting missing metrics.",
    commonMistakes: ["Forgetting empty lookup arrays are not null — pair with $first"],
    performanceTips: ["Defensive defaults keep downstream math safe"],
    related: ["$lookup", "$first", "$cond"],
  }),
  entry({
    stage: false,
    name: "$dateToString",
    category: "expression",
    syntax: '{ $dateToString: { format: "%Y-%m", date: "$createdAt" } }',
    purpose: "Formats a date into a string (e.g. '2025-01').",
    example: '{ $dateToString: { format: "%Y-%m-%d", date: "$createdAt" } }',
    exampleOutput: '"2025-01-15"',
    realWorld: "Monthly revenue buckets, cohort keys, report labels.",
    commonMistakes: ["Using the wrong format token (%m vs %M)", "Formatting a field that is already a string"],
    performanceTips: ["Bucketing by YYYY-MM sorts correctly as text"],
    related: ["$group", "$sort"],
  }),
  entry({
    stage: false,
    name: "$expr",
    category: "expression",
    syntax: '{ $expr: <expression> }',
    purpose: "Lets $match use aggregation expressions — compare fields, call functions, filter on computed values.",
    example: '{ $match: { $expr: { $gte: [{ $size: "$reviews" }, 5] } } }',
    exampleOutput: "Only products with 5 or more reviews.",
    realWorld: "Correlated sub-pipelines in $lookup, computed filters.",
    commonMistakes: ["Using plain field equality inside $expr unnecessarily", "Forgetting $expr cannot use index ranges as efficiently"],
    performanceTips: ["Keep $expr filters selective; index the fields involved"],
    related: ["$match", "$lookup", "$size", "$eq"],
  }),
  entry({
    stage: false,
    name: "$rank",
    category: "expression",
    syntax: '{ $rank: {} }',
    purpose: "Assigns 1 to the best row within a $setWindowFields partition, then increments by ties.",
    example: '{ output: { rank: { $rank: {} } } }',
    exampleOutput: "1 for the top movie of each year.",
    realWorld: "Podium charts, 'best of' lists, leaderboards.",
    commonMistakes: ["Using $denseRank when you need gap ranks", "Ranking without a sortBy"],
    performanceTips: ["Pair with partitionBy for per-group ranks, then $match to keep top-N"],
    related: ["$setWindowFields", "$sort", "$match"],
  }),
];
